source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftPlayer_Example', :exclusive => true do
  pod "SwiftPlayer", :path => "../"
end

target 'SwiftPlayer_Tests', :exclusive => true do
  pod "SwiftPlayer", :path => "../"

  
end
